# Generated by Django 3.2.4 on 2021-06-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
