# Generated by Django 3.2.4 on 2021-07-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='post',
        ),
    ]
